name: Automatic Lab Notebook Generator

on:
  push:
    branches:
      - main
    paths:
      - '**.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository with fetch-depth 2
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Extract current and previous .ipynb files
        id: extract-ipynbs
        run: |
          mkdir -p prev_notebooks
          INPUT_ARGS=""

          # get the most recent non-bot commit
          TRUE_PREV_COMMIT=$(git rev-list HEAD --max-count=1 --skip=1 --author='^(?!github-actions\[bot\])' --regexp-ignore-case)

          if [ -z "$TRUE_PREV_COMMIT" ]; then
            echo "Previous human-made commit not found; skipping ALN."
            exit 0
          fi

          for CURR_PATH in $(find . -maxdepth 1 -name "*.ipynb"); do
            CURR_NAME=$(basename "$CURR_PATH")

            echo "Found current notebook: $CURR_NAME"

            if git show "$TRUE_PREV_COMMIT":"$CURR_NAME" > "prev_notebooks/$CURR_NAME"; then
              echo "Recovered previous version of $CURR_NAME"
              INPUT_ARGS+=" prev_notebooks/$CURR_NAME $CURR_PATH"
            else
              echo "Previous version of $CURR_NAME not found; skipping notebook."
            fi
          done

          echo "FINAL_INPUT_ARGS=$INPUT_ARGS" >> $GITHUB_ENV

      - name: Execute ALN Python script and generate log
        run: |
          echo "Running main.py with inputs: $FINAL_INPUT_ARGS"
          mkdir -p aln_output
          python .github/workflows/main.py --input $FINAL_INPUT_ARGS --output ./aln_output/

      - name: Upload aln_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: aln_output
          path: aln_output/
          overwrite: true

      - name: Commit aln_output
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add aln_output/
          git commit -m "Generated aln_output from workflow"
          git push
        continue-on-error: true