name: Automatic Lab Notebook Generator

on:
  push:
    branches:
      - main
    paths:
      - '**.ipynb'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository with fetch-depth 2
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetches current and previous commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      - name: Get previous commit's ipynb file
        id: get-ipynb-path
        run: |
          CURR_IPYNB=$(find . -name "*.ipynb" | head -n 1)

          if [ -z "$CURR_IPYNB" ]; then
            echo "No .ipynb file found in the current commit. Exiting."
            exit 1
          fi
          echo "Current .ipynb file: $CURR_IPYNB"
          echo "CURR_IPYNB_PATH=$CURR_IPYNB" >> $GITHUB_ENV

          PREV_COMMIT_SHA=$(git rev-parse HEAD~1)
          PREV_IPYNB=$(git show $PREV_COMMIT_SHA --name-only --diff-filter=A --diff-filter=M | grep "$(basename "$CURR_IPYNB")" | head -n 1)

          if [ -z "$PREV_IPYNB" ]; then
            echo "No .ipynb file found in the previous commit, or it was deleted."
            exit 1
          fi

          git show $PREV_COMMIT_SHA:$PREV_IPYNB > prev_commit.ipynb
          echo "Copied previous commit's .ipynb file to prev_commit.ipynb"
          echo "PREV_IPYNB_PATH=prev_commit.ipynb" >> $GITHUB_ENV

      - name: Execute ALN Python script and generate log
        run: |
          echo "Executing main.py with:"
          echo "Current IPYNB: $CURR_IPYNB_PATH"
          echo "Previous IPYNB: $PREV_IPYNB_PATH"

          python .github/workflows/main.py \
            --curr "$CURRENT_IPYNB_PATH" \
            --prev "$PREVIOUS_IPYNB_PATH" \
            --output "./aln_output/"

      - name: Upload aln_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: aln_output
          path: aln_output/
          overwrite: true

      - name: Commit aln_output
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add aln_output/
          git commit -m "Generated aln_output from workflow"
          git push
        continue-on-error: true
